import { DataTable } from "@/components/custom/work-experience/data-table/data-table";
import { columns } from "@/components/custom/work-experience/data-table/columns";


async function getData() {
  return [
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
    {
      id: "728ed52f",
      position: "Software Engineer",
      tenure: "Jan 10 2015 - Dec 15 2023",
      company: "Google",
      description: "Forward Deployed key infastructure for Google maps.",
      outcomes: "Increased efficieny of maps application within Canary Wharf",
    },
  ]
}

export default async function  Page() {
  const data = await getData()
  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  );
}
